<?php
/**
 * Address
 *
 * PHP version 5
 *
 * @category Class
 * @package  Clickpag\
 * @author   http://github.com/clickpag-api/clickpag-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/clickpag-api/clickpag-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the clickpag code generator program.
 * https://github.com/clickpag-api/clickpag-codegen
 * Do not edit the class manually.
 */

namespace Clickpag\Model;

use \ArrayAccess;
/**
 * Address Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Clickpag\
 * @author      http://github.com/clickpag-api/clickpag-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/clickpag-api/clickpag-codegen
 */
class Address implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $clickpagTypes = array(
        'street' => 'string',
        'number' => 'string',
        'complement' => 'string',
        'postal_code' => 'string',
        'city' => 'string',
        'district' => 'string',
        'state' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'street' => 'street',
        'number' => 'number',
        'complement' => 'complement',
        'postal_code' => 'postalCode',
        'city' => 'city',
        'district' => 'district',
        'state' => 'state'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'street' => 'setStreet',
        'number' => 'setNumber',
        'complement' => 'setComplement',
        'postal_code' => 'setPostalCode',
        'city' => 'setCity',
        'district' => 'setDistrict',
        'state' => 'setState'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'street' => 'getStreet',
        'number' => 'getNumber',
        'complement' => 'getComplement',
        'postal_code' => 'getPostalCode',
        'city' => 'getCity',
        'district' => 'getDistrict',
        'state' => 'getState'
    );
  
    
    /**
      * $street Rua
      * @var string
      */
    protected $street;
    
    /**
      * $number Número
      * @var string
      */
    protected $number;
    
    /**
      * $complement Complemento
      * @var string
      */
    protected $complement;
    
    /**
      * $postal_code Número do cep
      * @var string
      */
    protected $postal_code;
    
    /**
      * $city Nome da cidade
      * @var string
      */
    protected $city;
    
    /**
      * $district Destrito
      * @var string
      */
    protected $district;
    
    /**
      * $state Nome do Estado
      * @var string
      */
    protected $state;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->street = $data["street"];
            $this->number = $data["number"];
            $this->complement = $data["complement"];
            $this->postal_code = $data["postal_code"];
            $this->city = $data["city"];
            $this->district = $data["district"];
            $this->state = $data["state"];
        }
    }
    
    /**
     * Gets street
     * @return string
     */
    public function getStreet()
    {
        return $this->street;
    }
  
    /**
     * Sets street
     * @param string $street Rua
     * @return $this
     */
    public function setStreet($street)
    {
        
        $this->street = $street;
        return $this;
    }
    
    /**
     * Gets number
     * @return string
     */
    public function getNumber()
    {
        return $this->number;
    }
  
    /**
     * Sets number
     * @param string $number Número
     * @return $this
     */
    public function setNumber($number)
    {
        
        $this->number = $number;
        return $this;
    }
    
    /**
     * Gets complement
     * @return string
     */
    public function getComplement()
    {
        return $this->complement;
    }
  
    /**
     * Sets complement
     * @param string $complement Complemento
     * @return $this
     */
    public function setComplement($complement)
    {
        
        $this->complement = $complement;
        return $this;
    }
    
    /**
     * Gets postal_code
     * @return string
     */
    public function getPostalCode()
    {
        return $this->postal_code;
    }
  
    /**
     * Sets postal_code
     * @param string $postal_code Número do cep
     * @return $this
     */
    public function setPostalCode($postal_code)
    {
        
        $this->postal_code = $postal_code;
        return $this;
    }
    
    /**
     * Gets city
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }
  
    /**
     * Sets city
     * @param string $city Nome da cidade
     * @return $this
     */
    public function setCity($city)
    {
        
        $this->city = $city;
        return $this;
    }
    
    /**
     * Gets district
     * @return string
     */
    public function getDistrict()
    {
        return $this->district;
    }
  
    /**
     * Sets district
     * @param string $district Destrito
     * @return $this
     */
    public function setDistrict($district)
    {
        
        $this->district = $district;
        return $this;
    }
    
    /**
     * Gets state
     * @return string
     */
    public function getState()
    {
        return $this->state;
    }
  
    /**
     * Sets state
     * @param string $state Nome do Estado
     * @return $this
     */
    public function setState($state)
    {
        
        $this->state = $state;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
