<?php
/**
 * Customer
 *
 * PHP version 5
 *
 * @category Class
 * @package  Clickpag\
 * @author   http://github.com/clickpag-api/clickpag-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/clickpag-api/clickpag-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the clickpag code generator program.
 * https://github.com/clickpag-api/clickpag-codegen
 * Do not edit the class manually.
 */

namespace Clickpag\Model;

use \ArrayAccess;
/**
 * Customer Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Clickpag\
 * @author      http://github.com/clickpag-api/clickpag-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/clickpag-api/clickpag-codegen
 */
class Customer implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $clickpagTypes = array(
        'name' => 'string',
        'email' => 'string',
        'documents' => '\Clickpag\Model\Document[]',
        'phones' => '\Clickpag\Model\Phone[]'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'name' => 'name',
        'email' => 'email',
        'documents' => 'documents',
        'phones' => 'phones'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'name' => 'setName',
        'email' => 'setEmail',
        'documents' => 'setDocuments',
        'phones' => 'setPhones'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'name' => 'getName',
        'email' => 'getEmail',
        'documents' => 'getDocuments',
        'phones' => 'getPhones'
    );
  
    
    /**
      * $name Nome do comprador
      * @var string
      */
    protected $name;
    
    /**
      * $email 
      * @var string
      */
    protected $email;
    
    /**
      * $documents Documentos do comprador
      * @var \Clickpag\Model\Document[]
      */
    protected $documents;
    
    /**
      * $phones Telefones do comprador
      * @var \Clickpag\Model\Phone[]
      */
    protected $phones;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->name = $data["name"];
            $this->email = $data["email"];
            $this->documents = $data["documents"];
            $this->phones = $data["phones"];
        }
    }
    
    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
  
    /**
     * Sets name
     * @param string $name Nome do comprador
     * @return $this
     */
    public function setName($name)
    {
        
        $this->name = $name;
        return $this;
    }
    
    /**
     * Gets email
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }
  
    /**
     * Sets email
     * @param string $email 
     * @return $this
     */
    public function setEmail($email)
    {
        
        $this->email = $email;
        return $this;
    }
    
    /**
     * Gets documents
     * @return \Clickpag\Model\Document[]
     */
    public function getDocuments()
    {
        return $this->documents;
    }
  
    /**
     * Sets documents
     * @param \Clickpag\Model\Document[] $documents Documentos do comprador
     * @return $this
     */
    public function setDocuments($documents)
    {
        
        $this->documents = $documents;
        return $this;
    }
    
    /**
     * Gets phones
     * @return \Clickpag\Model\Phone[]
     */
    public function getPhones()
    {
        return $this->phones;
    }
  
    /**
     * Sets phones
     * @param \Clickpag\Model\Phone[] $phones Telefones do comprador
     * @return $this
     */
    public function setPhones($phones)
    {
        
        $this->phones = $phones;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
