<?php
/**
 * Settings
 *
 * PHP version 5
 *
 * @category Class
 * @package  Clickpag\
 * @author   http://github.com/clickpag-api/clickpag-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/clickpag-api/clickpag-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the clickpag code generator program.
 * https://github.com/clickpag-api/clickpag-codegen
 * Do not edit the class manually.
 */

namespace Clickpag\Model;

use \ArrayAccess;
/**
 * Settings Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Clickpag\
 * @author      http://github.com/clickpag-api/clickpag-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/clickpag-api/clickpag-codegen
 */
class Settings implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $clickpagTypes = array(
        'expires_at' => '\DateTime',
        'attempts' => 'int',
        'max_installments' => 'Number'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'expires_at' => 'expiresAt',
        'attempts' => 'attempts',
        'max_installments' => 'maxInstallments'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'expires_at' => 'setExpiresAt',
        'attempts' => 'setAttempts',
        'max_installments' => 'setMaxInstallments'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'expires_at' => 'getExpiresAt',
        'attempts' => 'getAttempts',
        'max_installments' => 'getMaxInstallments'
    );
  
    
    /**
      * $expires_at Data de expiração do pedido
      * @var \DateTime
      */
    protected $expires_at;
    
    /**
      * $attempts Número de tentativas de pagamento do pedido
      * @var int
      */
    protected $attempts;
    
    /**
      * $max_installments Número máximo de parcelas aceita no pagamento deste pedido
      * @var Number
      */
    protected $max_installments;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->expires_at = $data["expires_at"];
            $this->attempts = $data["attempts"];
            $this->max_installments = $data["max_installments"];
        }
    }
    
    /**
     * Gets expires_at
     * @return \DateTime
     */
    public function getExpiresAt()
    {
        return $this->expires_at;
    }
  
    /**
     * Sets expires_at
     * @param \DateTime $expires_at Data de expiração do pedido
     * @return $this
     */
    public function setExpiresAt($expires_at)
    {
        
        $this->expires_at = $expires_at;
        return $this;
    }
    
    /**
     * Gets attempts
     * @return int
     */
    public function getAttempts()
    {
        return $this->attempts;
    }
  
    /**
     * Sets attempts
     * @param int $attempts Número de tentativas de pagamento do pedido
     * @return $this
     */
    public function setAttempts($attempts)
    {
        
        $this->attempts = $attempts;
        return $this;
    }
    
    /**
     * Gets max_installments
     * @return Number
     */
    public function getMaxInstallments()
    {
        return $this->max_installments;
    }
  
    /**
     * Sets max_installments
     * @param Number $max_installments Número máximo de parcelas aceita no pagamento deste pedido
     * @return $this
     */
    public function setMaxInstallments($max_installments)
    {
        
        $this->max_installments = $max_installments;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
