<?php
/**
 * Transaction
 *
 * PHP version 5
 *
 * @category Class
 * @package  Clickpag\
 * @author   http://github.com/clickpag-api/clickpag-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/clickpag-api/clickpag-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the clickpag code generator program.
 * https://github.com/clickpag-api/clickpag-codegen
 * Do not edit the class manually.
 */

namespace Clickpag\Model;

use \ArrayAccess;
/**
 * Transaction Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Clickpag\
 * @author      http://github.com/clickpag-api/clickpag-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/clickpag-api/clickpag-codegen
 */
class Transaction implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $clickpagTypes = array(
        'id' => 'string',
        'creation_date' => '\DateTime',
        'status' => 'string',
        'customer_name' => 'string',
        'customer_email' => 'string',
        'amount' => 'int',
        'payment_method' => 'string',
        'card_brand' => 'string',
        'installments' => 'int',
        'reference' => 'string',
        't_id' => 'string',
        'nsu' => 'string',
        'shipping' => '\Clickpag\Model\Shipping',
        'items' => '\Clickpag\Model\Item[]',
        'status_history' => '\Clickpag\Model\StatusHistory[]'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id' => 'id',
        'creation_date' => 'creationDate',
        'status' => 'status',
        'customer_name' => 'customerName',
        'customer_email' => 'customerEmail',
        'amount' => 'amount',
        'payment_method' => 'paymentMethod',
        'card_brand' => 'cardBrand',
        'installments' => 'installments',
        'reference' => 'reference',
        't_id' => 'tId',
        'nsu' => 'nsu',
        'shipping' => 'shipping',
        'items' => 'items',
        'status_history' => 'statusHistory'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id' => 'setId',
        'creation_date' => 'setCreationDate',
        'status' => 'setStatus',
        'customer_name' => 'setCustomerName',
        'customer_email' => 'setCustomerEmail',
        'amount' => 'setAmount',
        'payment_method' => 'setPaymentMethod',
        'card_brand' => 'setCardBrand',
        'installments' => 'setInstallments',
        'reference' => 'setReference',
        't_id' => 'setTId',
        'nsu' => 'setNsu',
        'shipping' => 'setShipping',
        'items' => 'setItems',
        'status_history' => 'setStatusHistory'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id' => 'getId',
        'creation_date' => 'getCreationDate',
        'status' => 'getStatus',
        'customer_name' => 'getCustomerName',
        'customer_email' => 'getCustomerEmail',
        'amount' => 'getAmount',
        'payment_method' => 'getPaymentMethod',
        'card_brand' => 'getCardBrand',
        'installments' => 'getInstallments',
        'reference' => 'getReference',
        't_id' => 'getTId',
        'nsu' => 'getNsu',
        'shipping' => 'getShipping',
        'items' => 'getItems',
        'status_history' => 'getStatusHistory'
    );
  
    
    /**
      * $id Id da transação
      * @var string
      */
    protected $id;
    
    /**
      * $creation_date Data de criação
      * @var \DateTime
      */
    protected $creation_date;
    
    /**
      * $status status da transação
      * @var string
      */
    protected $status;
    
    /**
      * $customer_name Nome do pagador
      * @var string
      */
    protected $customer_name;
    
    /**
      * $customer_email Email do pagador
      * @var string
      */
    protected $customer_email;
    
    /**
      * $amount Valor da transação
      * @var int
      */
    protected $amount;
    
    /**
      * $payment_method Método de pagamento
      * @var string
      */
    protected $payment_method;
    
    /**
      * $card_brand Bandeira do  cartão
      * @var string
      */
    protected $card_brand;
    
    /**
      * $installments Quantidade de parcelas
      * @var int
      */
    protected $installments;
    
    /**
      * $reference Id da order origem da transação
      * @var string
      */
    protected $reference;
    
    /**
      * $t_id Número da transação na base do lojista
      * @var string
      */
    protected $t_id;
    
    /**
      * $nsu Número de sequencia do lojista
      * @var string
      */
    protected $nsu;
    
    /**
      * $shipping Dados da entrega
      * @var \Clickpag\Model\Shipping
      */
    protected $shipping;
    
    /**
      * $items Produtos do carrinho
      * @var \Clickpag\Model\Item[]
      */
    protected $items;
    
    /**
      * $status_history Historico de alteração do status
      * @var \Clickpag\Model\StatusHistory[]
      */
    protected $status_history;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->id = $data["id"];
            $this->creation_date = $data["creation_date"];
            $this->status = $data["status"];
            $this->customer_name = $data["customer_name"];
            $this->customer_email = $data["customer_email"];
            $this->amount = $data["amount"];
            $this->payment_method = $data["payment_method"];
            $this->card_brand = $data["card_brand"];
            $this->installments = $data["installments"];
            $this->reference = $data["reference"];
            $this->t_id = $data["t_id"];
            $this->nsu = $data["nsu"];
            $this->shipping = $data["shipping"];
            $this->items = $data["items"];
            $this->status_history = $data["status_history"];
        }
    }
    
    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param string $id Id da transação
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets creation_date
     * @return \DateTime
     */
    public function getCreationDate()
    {
        return $this->creation_date;
    }
  
    /**
     * Sets creation_date
     * @param \DateTime $creation_date Data de criação
     * @return $this
     */
    public function setCreationDate($creation_date)
    {
        
        $this->creation_date = $creation_date;
        return $this;
    }
    
    /**
     * Gets status
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }
  
    /**
     * Sets status
     * @param string $status status da transação
     * @return $this
     */
    public function setStatus($status)
    {
        $allowed_values = array("REVERSED", "APPROVED", "IN_DISPUTE", "CHARGEBACK", "IN_ANALISYS", "DENIED");
        if (!in_array($status, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'status', must be one of 'REVERSED', 'APPROVED', 'IN_DISPUTE', 'CHARGEBACK', 'IN_ANALISYS', 'DENIED'");
        }
        $this->status = $status;
        return $this;
    }
    
    /**
     * Gets customer_name
     * @return string
     */
    public function getCustomerName()
    {
        return $this->customer_name;
    }
  
    /**
     * Sets customer_name
     * @param string $customer_name Nome do pagador
     * @return $this
     */
    public function setCustomerName($customer_name)
    {
        
        $this->customer_name = $customer_name;
        return $this;
    }
    
    /**
     * Gets customer_email
     * @return string
     */
    public function getCustomerEmail()
    {
        return $this->customer_email;
    }
  
    /**
     * Sets customer_email
     * @param string $customer_email Email do pagador
     * @return $this
     */
    public function setCustomerEmail($customer_email)
    {
        
        $this->customer_email = $customer_email;
        return $this;
    }
    
    /**
     * Gets amount
     * @return int
     */
    public function getAmount()
    {
        return $this->amount;
    }
  
    /**
     * Sets amount
     * @param int $amount Valor da transação
     * @return $this
     */
    public function setAmount($amount)
    {
        
        $this->amount = $amount;
        return $this;
    }
    
    /**
     * Gets payment_method
     * @return string
     */
    public function getPaymentMethod()
    {
        return $this->payment_method;
    }
  
    /**
     * Sets payment_method
     * @param string $payment_method Método de pagamento
     * @return $this
     */
    public function setPaymentMethod($payment_method)
    {
        
        $this->payment_method = $payment_method;
        return $this;
    }
    
    /**
     * Gets card_brand
     * @return string
     */
    public function getCardBrand()
    {
        return $this->card_brand;
    }
  
    /**
     * Sets card_brand
     * @param string $card_brand Bandeira do  cartão
     * @return $this
     */
    public function setCardBrand($card_brand)
    {
        $allowed_values = array("VISA", "MASTERCARD", "DINERS", "HIPER", "HIPERCARD");
        if (!in_array($card_brand, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'card_brand', must be one of 'VISA', 'MASTERCARD', 'DINERS', 'HIPER', 'HIPERCARD'");
        }
        $this->card_brand = $card_brand;
        return $this;
    }
    
    /**
     * Gets installments
     * @return int
     */
    public function getInstallments()
    {
        return $this->installments;
    }
  
    /**
     * Sets installments
     * @param int $installments Quantidade de parcelas
     * @return $this
     */
    public function setInstallments($installments)
    {
        
        $this->installments = $installments;
        return $this;
    }
    
    /**
     * Gets reference
     * @return string
     */
    public function getReference()
    {
        return $this->reference;
    }
  
    /**
     * Sets reference
     * @param string $reference Id da order origem da transação
     * @return $this
     */
    public function setReference($reference)
    {
        
        $this->reference = $reference;
        return $this;
    }
    
    /**
     * Gets t_id
     * @return string
     */
    public function getTId()
    {
        return $this->t_id;
    }
  
    /**
     * Sets t_id
     * @param string $t_id Número da transação na base do lojista
     * @return $this
     */
    public function setTId($t_id)
    {
        
        $this->t_id = $t_id;
        return $this;
    }
    
    /**
     * Gets nsu
     * @return string
     */
    public function getNsu()
    {
        return $this->nsu;
    }
  
    /**
     * Sets nsu
     * @param string $nsu Número de sequencia do lojista
     * @return $this
     */
    public function setNsu($nsu)
    {
        
        $this->nsu = $nsu;
        return $this;
    }
    
    /**
     * Gets shipping
     * @return \Clickpag\Model\Shipping
     */
    public function getShipping()
    {
        return $this->shipping;
    }
  
    /**
     * Sets shipping
     * @param \Clickpag\Model\Shipping $shipping Dados da entrega
     * @return $this
     */
    public function setShipping($shipping)
    {
        
        $this->shipping = $shipping;
        return $this;
    }
    
    /**
     * Gets items
     * @return \Clickpag\Model\Item[]
     */
    public function getItems()
    {
        return $this->items;
    }
  
    /**
     * Sets items
     * @param \Clickpag\Model\Item[] $items Produtos do carrinho
     * @return $this
     */
    public function setItems($items)
    {
        
        $this->items = $items;
        return $this;
    }
    
    /**
     * Gets status_history
     * @return \Clickpag\Model\StatusHistory[]
     */
    public function getStatusHistory()
    {
        return $this->status_history;
    }
  
    /**
     * Sets status_history
     * @param \Clickpag\Model\StatusHistory[] $status_history Historico de alteração do status
     * @return $this
     */
    public function setStatusHistory($status_history)
    {
        
        $this->status_history = $status_history;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
